# Generated by Django 4.0.3 on 2022-03-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='communityitem',
            name='qr_code',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
