# Generated by Django 3.2.7 on 2022-05-25 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityItemGroupThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('community', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.community')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communityitem')),
                ('itemGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.communityitemgroup')),
            ],
        ),
        migrations.AddField(
            model_name='communityitemgroup',
            name='items',
            field=models.ManyToManyField(blank=True, through='main.CommunityItemGroupThrough', to='main.CommunityItem'),
        ),
    ]
