# Generated by Django 3.2.7 on 2022-05-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_communityitemgroup_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitemgroup',
            name='group_id',
            field=models.CharField(default=None, max_length=28, null=True),
        ),
    ]
