# Generated by Django 4.0.3 on 2022-03-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_communityitem_item_id_communityitem_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityitem',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='communityitem',
            name='qr_code_image',
            field=models.ImageField(default=None, editable=False, null=True, upload_to='qrcodes'),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, editable=False, max_length=200, null=True),
        ),
    ]
