# Generated by Django 3.2.7 on 2022-05-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_communityitemgroup_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityitemgroupthrough',
            old_name='itemGroup',
            new_name='group',
        ),
    ]
