# Generated by Django 3.2.7 on 2022-03-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_communityitem_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, editable=False, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='qr_code_image',
            field=models.ImageField(default=None, editable=False, null=True, upload_to='generated_codes'),
        ),
    ]
