# Generated by Django 3.2.7 on 2022-03-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220312_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='community',
            name='nameID',
            field=models.CharField(editable=False, max_length=108, primary_key=True, serialize=False),
        ),
    ]
