# Generated by Django 3.2.7 on 2022-05-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_communityitemgroup_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityitemgroupthrough',
            old_name='count',
            new_name='alive',
        ),
        migrations.AddField(
            model_name='communityitemgroupthrough',
            name='dead',
            field=models.IntegerField(default=0),
        ),
    ]
