# Generated by Django 3.2.7 on 2022-03-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220312_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, max_length=48, null=True),
        ),
    ]
