# Generated by Django 3.2.7 on 2022-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_communityitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, editable=False, max_length=48, null=True),
        ),
    ]
