# Generated by Django 3.2.7 on 2022-06-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220613_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitemgroup',
            name='latitude',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='communityitemgroup',
            name='longitude',
            field=models.FloatField(default=None, null=True),
        ),
    ]
