# Generated by Django 3.2.7 on 2022-03-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_communityitem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitem',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='qr_code_image',
            field=models.ImageField(default=None, editable=False, null=True, upload_to='generated_codes/'),
        ),
    ]
