# Generated by Django 3.2.7 on 2022-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220312_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitem',
            name='qr_code_image',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to='generated_codes/'),
        ),
    ]
