# Generated by Django 3.2.7 on 2022-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_communityitem_qr_code_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityitem',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='item_images/'),
        ),
    ]
