# Generated by Django 3.2.7 on 2022-03-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_communityitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitem',
            name='hasImage',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
