# Generated by Django 3.2.7 on 2022-03-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_communityitem_hasimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityitem',
            name='qr_code_image',
        ),
        migrations.AddField(
            model_name='community',
            name='hasEditedItemsSinceLastPrint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='item_id',
            field=models.CharField(default=None, editable=False, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
