# Generated by Django 3.2.7 on 2022-03-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_community_hasediteditemssincelastprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityitem',
            name='hasImage',
        ),
        migrations.RemoveField(
            model_name='communityitem',
            name='image',
        ),
    ]
